<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Report extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        if (!$this->ion_auth->logged_in()) {//cek login ga?
            redirect('login','refresh');
        }else{
            if (!$this->ion_auth->in_group('members')) {//cek admin ga?
                redirect('login','refresh');
            }
        }
        //$this->load->model('order/Pesanan_model');
        $this->load->model('Report_model');
    }

    public function pdf()
  	{
  		$this->load->library('Pdfgenerator');

  		$data['users']=array(
  			array('firstname'=>'Agung','lastname'=>'Setiawan','email'=>'ag@setiawan.com'),
  			array('firstname'=>'Hauril','lastname'=>'Maulida Nisfar','email'=>'hm@setiawan.com'),
  			array('firstname'=>'Akhtar','lastname'=>'Setiawan','email'=>'akh@setiawan.com'),
  			array('firstname'=>'Gitarja','lastname'=>'Setiawan','email'=>'git@setiawan.com')
  		);

  	    $html = $this->load->view('table_report', $data, true);

  	    $this->pdfgenerator->generate($html,'contoh');
  	}

    public function index()
    {
      # code...
        $data['aktif']      ='Premium';
        $data['title']       ='Admin Panel';
        $data['judul_menu']  ='Braja Marketindo';
        $data['nama_jln']    ='Jl.Lotus Timur, Jakasetia, Jawa Barat';
        //$data['pesanan'] = $this->Pesanan_model->total_baru();
        $data['data']=$this->Report_model->get_all();
        $data['record']		= $this->Report_model->get_produk();
		    $this->load->view('chart', $data);

    }

    public function laba()
    {
      # code...
      $date1 = $this->input->post('date_from');
      $date2 = $this->input->post('date_to');
      $data = array(
        'date1' => $date1,
        'date2' => $date2
      );
      if ($date1 == "" || $date2 == "") {
      $data['date_range_error_message'] = "Both date fields are required";
      } else {
      $result = $this->Report_model->show_laba_by_date_range($data);
      if ($result != false) {
      $data['result_display'] = $result;
      } else {
      $data['result_display'] = "No record found !";
      }
      }
      $data['aktif']      ='Premium';
      $data['title']       ='Admin Panel';
      $data['judul_menu']  ='Braja Marketindo';
      $data['nama_jln']    ='Jl.Lotus Timur, Jakasetia, Jawa Barat';
      $data['pesanan'] = $this->Pesanan_model->total_baru();
      $data['data']=$this->Report_model->get_all();
      $data['record']		= $this->Report_model->get_produk();
      $data['show_table'] = $this->view_table();
      $this->load->view('reportlaba', $data);
    }

    public function view_table(){
        $result = $this->Report_model->show_all_data();
        if ($result != false) {
        return $result;
        } else {
        return 'Database is empty !';
        }
    }

    public function chart()
    {
        foreach($this->Report_model->get_all()->result_array() as $row)
  			{
  				$data[] = array(
  					'hasil' => $row['hasil'],
  					'hit' => $row['hit']
  				  );
  			}
  			echo json_encode($data);
  	}

    public function excel()
    {
        $this->load->helper('exportexcel');
        $namaFile = "produkterlaris.xls";
        $judul = "Data 10 Produk Populer";
        $tablehead = 0;
        $tablebody = 1;
        $nourut = 1;
        //penulisan header
        header("Pragma: public");
        header("Expires: 0");
        header("Cache-Control: must-revalidate, post-check=0,pre-check=0");
        header("Content-Type: application/force-download");
        header("Content-Type: application/octet-stream");
        header("Content-Type: application/download");
        header("Content-Disposition: attachment;filename=" . $namaFile . "");
        header("Content-Transfer-Encoding: binary ");

        xlsBOF();

        $kolomhead = 0;
        xlsWriteLabel($tablehead, $kolomhead++, "No");
	xlsWriteLabel($tablehead, $kolomhead++, "Nama Produk");
	xlsWriteLabel($tablehead, $kolomhead++, "Dilihat");
	xlsWriteLabel($tablehead, $kolomhead++, "Tanggal Entry");

	foreach ($this->Report_model->get_produk() as $data) {
            $kolombody = 0;

            //ubah xlsWriteLabel menjadi xlsWriteNumber untuk kolom numeric
            xlsWriteNumber($tablebody, $kolombody++, $nourut);
	    xlsWriteLabel($tablebody, $kolombody++, $data->nama_produk);
	    xlsWriteLabel($tablebody, $kolombody++, $data->hit);
	    xlsWriteLabel($tablebody, $kolombody++, $data->tgl_entry);

	    $tablebody++;
            $nourut++;
        }

        xlsEOF();
        exit();
    }

}

/* End of file Order.php */
/* Location: ./application/controllers/Order.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-13 05:41:34 */
/* http://harviacode.com */
