<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Depan_model extends CI_Model
{

    public $table = 'pengunjung';
    public $table1 = 'buku';
    public $id = 'id';
    public $id_buku = 'id_buku';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
    $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('jenis_kelamin', $q);
	$this->db->or_like('jenis', $q);
	$this->db->or_like('perlu', $q);
	$this->db->or_like('saran', $q);
	$this->db->or_like('tgl', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('jenis_kelamin', $q);
	$this->db->or_like('jenis', $q);
	$this->db->or_like('perlu', $q);
	$this->db->or_like('saran', $q);
	$this->db->or_like('tgl', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    public function buat_kode(){
        $this->db->select('RIGHT(pengunjung.id, 2) as kode', FALSE);
        $this->db->order_by($this->id, $this->order);
        $this->db->limit(1);
        $query = $this->db->get($this->table, $this->id);
        if ($query->num_rows() <> 0) {
            $data = $query->row();
            $kode = intval($data->kode) + 1;
        } else {
            $kode = 1;
        }
        $kodemax = str_pad($kode, 2, "0", STR_PAD_LEFT);
        $kodejadi = "P000".$kodemax;
        return $kodejadi;
    }

    /*function get_buku($search){

        $query = $this
                ->db
                ->select('buku.gambar, buku.judul, buku.pengarang, buku.penerbit, rak_buku.lokasi, rak_buku.bagian')
                ->from('buku')
                ->join('rak_buku, rak_buku.kode_rak=buku.kode_rak')
                ->like('buku.judul',$search)
                ->or_like('buku.pengarang',$search)
                ->or_like('buku.penerbit',$search)
                ->order_by('buku.judul')
                ->get();
     
        if($query->num_rows() == 0)
        {
            //return $query->result(); 
            echo '<tr><td colspan="7"><center><div class="alert alert-danger" role="alert">Buku dengan keyword "'.$search.'" tidak ditemukan</div></center></td></tr>';
        } else {
          return $query->result();
        }     
    }*/

    function get_buku($search) {
      $this->db->select("buku.gambar, buku.judul, buku.pengarang, buku.penerbit, rak_buku.lokasi, rak_buku.bagian");
      $this->db->from($this->table1);
      $this->db->join('rak_buku', 'rak_buku.kode_rak = buku.kode_rak');
      $this->db->like('judul', $search);
      $this->db->or_like('pengarang', $search);
      $this->db->or_like('penerbit', $search);
      $this->db->order_by('judul', $this->order);
      $query = $this->db->get();
      if($query->num_rows() == 0)
        {
            //return $query->result(); 
            echo '<tr><td colspan="7"><center><div class="alert alert-danger" role="alert">Buku dengan keyword "'.$search.'" tidak ditemukan</div></center></td></tr>';
        } else {
          return $query->result();
        }
    }

}

/* End of file Pengunjung_model.php */
/* Location: ./application/models/Pengunjung_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-18 03:44:06 */
/* http://harviacode.com */