<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Buku_model extends CI_Model
{

    public $table = 'buku';
    public $tabel1 = 'transaksi';
    public $id = 'id_buku';
    public $id_buku = 'id_buku';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get total rows
    function total_record($q = NULL){
        $this->db->like('id_buku', $q);
        $this->db->or_like('kode_buku', $q);
        $this->db->or_like('ISBN', $q);
        $this->db->or_like('judul', $q);
        $this->db->or_like('pengarang', $q);
        $this->db->or_like('penerbit', $q);
        $this->db->or_like('tahun_terbit', $q);
        $this->db->or_like('stok', $q);
        $this->db->or_like('created_at', $q);
        $this->db->or_like('updated_at', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    function buku_limit($limit, $no = 0, $q = NULL){
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_buku', $q);
        $this->db->or_like('kode_buku', $q);
        $this->db->or_like('ISBN', $q);
        $this->db->or_like('judul', $q);
        $this->db->or_like('pengarang', $q);
        $this->db->or_like('penerbit', $q);
        $this->db->or_like('tahun_terbit', $q);
        $this->db->or_like('stok', $q);
        $this->db->or_like('created_at', $q);
        $this->db->or_like('updated_at', $q);
        $this->db->limit($limit, $no);
        return $this->db->get($this->table);
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {   
        $this->db->where($this->id, $id);
        //$this->db->delete($this->table);
        $delete = $this->db->get($this->table);
        $row = $delete->row();
        unlink("./assets/buku/$row->gambar");
        $hapus = $this->db->delete($this->table, array($this->id => $id));
        return $hapus;
    }

    //cek status buku di table transaksi
    function cek_status($id_buku){
        $this->db->where($this->id_buku, $id_buku);
        $this->db->where('status', 'pinjam');
        $cek = $this->db->get($this->tabel1);
        if ($cek->num_rows() > 0) {
            return TRUE;
        } else return FALSE;
    }

    function get_allbuku($batas =null,$offset=null,$key=null) {
        $this->db->from($this->table);
        if($batas != null){
           $this->db->limit($batas,$offset);
        }
        if ($key != null) {
           $this->db->or_like($key);
        }
        $this->db->order_by($this->id, $this->order);
        $query = $this->db->get();
 
        //cek apakah ada barang
        if ($query->num_rows() > 0) {
            return $query->result();
            }
    }

    function count_buku(){
        $query = $this->db->get($this->table)->num_rows();
        return $query;
        }

    function  count_buku_search($orlike) {
        $this->db->or_like($orlike);
        $query = $this->db->get($this->table);
 
        return $query->num_rows();
    }

    public function buat_kode()   {
          $this->db->select('RIGHT(buku.id_buku, 2) as kode', FALSE);
          $this->db->order_by($this->id, $this->order);
          $this->db->limit(1);
          $query = $this->db->get($this->table, $this->id);      //cek dulu apakah ada sudah ada kode di tabel.
          if($query->num_rows() <> 0){
           //jika kode ternyata sudah ada.
           $data = $query->row();
           $kode = intval($data->kode) + 1;
          }
          else {
           //jika kode belum ada
           $kode = 1;
          }
          $kodemax = str_pad($kode, 2, "0", STR_PAD_LEFT); // angka 4 menunjukkan jumlah digit angka 0
          $kodejadi = "1100".$kodemax;    // hasilnya ODJ-9921-0001 dst.
          return $kodejadi;
    }

}

/* End of file Buku_model.php */
/* Location: ./application/models/Buku_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-11-27 05:32:23 */
/* http://harviacode.com */