<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kelas_model extends CI_Model
{

    public $table = 'kelas';
    public $id = 'id_kelas';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_kelas', $q);
	$this->db->or_like('kelas', $q);
	$this->db->or_like('jurusan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_kelas', $q);
      	$this->db->or_like('kelas', $q);
      	$this->db->or_like('jurusan', $q);
      	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // cek id_kelas anggota peminjam buku
    function cek_idkelas($id_kelas){
        $this->db->where($this->id, $id_kelas);
        $cek = $this->db->get('anggota');
        if ($cek->num_rows() > 0) {
          return TRUE;
        } else return FALSE;
    }

    function get_allkelas($batas =null,$offset=null,$key=null) {
        $this->db->order_by($this->id, $this->order);
        $this->db->from($this->table);
        if($batas != null){
           $this->db->limit($batas,$offset);
        }
        if ($key != null) {
           $this->db->or_like($key);
        }
        $query = $this->db->get();

        //cek apakah ada barang
        if ($query->num_rows() > 0) {
            return $query->result();
            }
    }

    function count_kelas(){
        $query = $this->db->get($this->table)->num_rows();
        return $query;
        }

    function  count_kelas_search($orlike) {
        $this->db->or_like($orlike);
        $query = $this->db->get($this->table);

        return $query->num_rows();
    }

    public function buat_kode()   {
          $this->db->select('RIGHT(kelas.id_kelas, 2) as kode', FALSE);
          $this->db->order_by($this->id, $this->order);
          $this->db->limit(1);
          $query = $this->db->get($this->table, $this->id);      //cek dulu apakah ada sudah ada kode di tabel.
          if($query->num_rows() <> 0){
           //jika kode ternyata sudah ada.
           $data = $query->row();
           $kode = intval($data->kode) + 1;
          }
          else {
           //jika kode belum ada
           $kode = 1;
          }
          $kodemax = str_pad($kode, 2, "0", STR_PAD_LEFT); // angka 4 menunjukkan jumlah digit angka 0
          $kodejadi = "1230".$kodemax;    // hasilnya ODJ-9921-0001 dst.
          return $kodejadi;
    }

}

/* End of file Kelas_model.php */
/* Location: ./application/models/Kelas_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-03 14:53:01 */
/* http://harviacode.com */
