<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Rak_buku_model extends CI_Model
{

    public $table = 'rak_buku';
    public $id = 'kode_rak';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('kode_rak', $q);
	$this->db->or_like('lokasi', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('kode_rak', $q);
	$this->db->or_like('lokasi', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // cek id_kelas anggota peminjam buku
    function cek_koderak($kode_rak){
        $this->db->where($this->id, $kode_rak);
        $cek = $this->db->get('buku');
        if ($cek->num_rows() > 0) {
          return TRUE;
        } else return FALSE;
    }

    public function buat_kode()   {
          $this->db->select('RIGHT(rak_buku.kode_rak, 2) as kode', FALSE);
          $this->db->order_by($this->id, $this->order);
          $this->db->limit(1);
          $query = $this->db->get($this->table, $this->id);      //cek dulu apakah ada sudah ada kode di tabel.
          if($query->num_rows() <> 0){
           //jika kode ternyata sudah ada.
           $data = $query->row();
           $kode = intval($data->kode) + 1;
          }
          else {
           //jika kode belum ada
           $kode = 1;
          }
          $kodemax = str_pad($kode, 2, "0", STR_PAD_LEFT); // angka 2 menunjukkan jumlah digit angka 0
          $kodejadi = "RB00".$kodemax;    // hasilnya ODJ-9921-0001 dst.
          return $kodejadi;
    }

}

/* End of file Rak_buku_model.php */
/* Location: ./application/models/Rak_buku_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-27 03:30:16 */
/* http://harviacode.com */